[package]
name = "feynman_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.7.13"
pest_derive = "2.7.13"
wasm-minimal-protocol = { git = "https://github.com/astrale-sharp/wasm-minimal-protocol/" }
