// https://pest.rs/?g=N4Ig5gTghgtjURALhAdQBIEkAqBRAygAoCCAwrgAQC8FA%2BsBQDohMsA%2BrjjALsxQL6MAdgDlcqADKYxFWdToNmXIXw5LGEZX0EqhANwCmEbgYAecuTUUhDxs6woA-CgEsAJgaHcXAMxdGAagFhFy8jKABjbwB7IXkGd09vPyMnCgQIaIB3NMSvX38IYN0fIxgXWPkAAWsAWgA%2BbWEABwALaO5K6utHRpYdDOzLBQpSiHLKjjaOyp0Qj3yUopoaimJ8UkxMWmIJQnRiEQBVAFlcACVMUiC5oTcXKEhYeIoAClfbE3MOUJNoKIqQgAlGkxJJpLgAkCbsIQAAaEChZoAV24yBsRi%2BFGmnSEAEZse1cQAmdKmQHCKDkyq9QkzfGU6lxWk42LE2EIgDOBgANgYogY3OdkXz0fdHtAYCB%2BEA#editor

WHITESPACE = _{ " " | "\t" }
NEWLINE    = _{ "\n" | "\r\n" }

vertex      = { "vertex " ~ identifier+ }
interaction = { identifier ~ arrow ~ identifier }

fermion = @{ "->" }
photon  = @{ "~>" }
arrow   = _{ fermion | photon }

identifier = @{ ASCII_ALPHANUMERIC+ }

diagram = { ((vertex | interaction) ~ NEWLINE+)+ }
