WHITESPACE = _{ " " | "\t" }
NEWLINE    = _{ "\n" | "\r\n" }

vertex      = { "vertex " ~ identifier+ }
interaction = { identifier ~ arrow ~ identifier }

fermion  = @{ "->" | "<-" }
photon   = @{ "~p~" }
z_boson  = @{ "~Z~" }
w_boson  = @{ "~W~" }
gluon    = @{ "~g~" }
graviton = @{ "~G~" }

arrow = _{ fermion | photon | z_boson | w_boson | gluon | graviton }

identifier = @{ ASCII_ALPHANUMERIC+ }

diagram = { ((vertex | interaction) ~ NEWLINE+)+ }
